import { SavedLink } from '@/types';

export const mockLinks: SavedLink[] = [
  // 今日の記事（4つ）
  {
    id: '1',
    url: 'https://example.com/article-1',
    title: 'React Native の新機能について',
    description:
      'React Native の最新アップデートと新機能について詳しく解説します。',
    thumbnail:
      'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['react-native', 'development', 'technology'],
    createdAt: new Date(),
    updatedAt: new Date(),
    isRead: false,
    readingTime: 8,
    source: 'TechBlog',
  },
  {
    id: '2',
    url: 'https://example.com/article-2',
    title: 'TypeScript ベストプラクティス',
    description: 'TypeScript を使った効率的な開発手法を紹介します。',
    thumbnail:
      'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['typescript', 'javascript', 'development'],
    createdAt: new Date(),
    updatedAt: new Date(),
    isRead: false,
    readingTime: 10,
    source: 'Dev Weekly',
  },
  {
    id: '3',
    url: 'https://example.com/article-3',
    title: 'モバイルアプリデザインのトレンド',
    description: '2024年のモバイルアプリデザインで注目すべきトレンドについて',
    thumbnail:
      'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['design', 'mobile', 'ui-ux'],
    createdAt: new Date(),
    updatedAt: new Date(),
    isRead: false,
    readingTime: 6,
    source: 'Design Trends',
  },
  {
    id: '4',
    url: 'https://example.com/article-4',
    title: 'AI を活用した開発ツール',
    description: 'AI を使って開発効率を向上させる最新のツールについて紹介',
    thumbnail:
      'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['ai', 'tools', 'productivity'],
    createdAt: new Date(),
    updatedAt: new Date(),
    isRead: false,
    readingTime: 12,
    source: 'AI Weekly',
  },

  // 昨日の記事（2つ）
  {
    id: '5',
    url: 'https://example.com/article-5',
    title: 'Webアクセシビリティの基本',
    description: '誰でも使いやすいWebサイトを作るためのアクセシビリティガイド',
    thumbnail:
      'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['accessibility', 'web', 'ux'],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 15,
    source: 'UX Guide',
  },
  {
    id: '6',
    url: 'https://example.com/article-6',
    title: 'パフォーマンス最適化の手法',
    description: 'Webアプリケーションのパフォーマンスを向上させる実践的な手法',
    thumbnail:
      'https://images.pexels.com/photos/414102/pexels-photo-414102.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['performance', 'optimization', 'web'],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 9,
    source: 'Performance Blog',
  },

  // 3日前の記事（5つ）
  {
    id: '7',
    url: 'https://example.com/article-7',
    title: 'GraphQL vs REST API',
    description: 'GraphQL と REST API の違いと使い分けについて詳しく解説',
    thumbnail:
      'https://images.pexels.com/photos/574069/pexels-photo-574069.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['graphql', 'api', 'backend'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 11,
    source: 'API Guide',
  },
  {
    id: '8',
    url: 'https://example.com/article-8',
    title: 'CSS Grid レイアウト完全ガイド',
    description: 'CSS Grid を使った柔軟で効率的なレイアウト設計の方法',
    thumbnail:
      'https://images.pexels.com/photos/326333/pexels-photo-326333.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['css', 'layout', 'frontend'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 14,
    source: 'CSS Tricks',
  },
  {
    id: '9',
    url: 'https://example.com/article-9',
    title: 'セキュリティベストプラクティス',
    description: 'Webアプリケーション開発におけるセキュリティの基本と実践',
    thumbnail:
      'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['security', 'web', 'backend'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 18,
    source: 'Security Hub',
  },
  {
    id: '10',
    url: 'https://example.com/article-10',
    title: 'Docker コンテナ入門',
    description: 'Docker を使った効率的な開発環境の構築方法',
    thumbnail:
      'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['docker', 'devops', 'containers'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 16,
    source: 'DevOps Weekly',
  },
  {
    id: '11',
    url: 'https://example.com/article-11',
    title: 'ユーザビリティテストの手法',
    description: '効果的なユーザビリティテストの計画と実施方法',
    thumbnail:
      'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['usability', 'testing', 'ux'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: false,
    readingTime: 13,
    source: 'UX Research',
  },

  // 既読記事（5つ）
  {
    id: '12',
    url: 'https://example.com/article-12',
    title: 'Vue.js 3 の新機能',
    description: 'Vue.js 3 で追加された新機能と従来バージョンからの変更点',
    thumbnail:
      'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['vue', 'frontend', 'javascript'],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    isRead: true,
    readingTime: 12,
    source: 'Vue Weekly',
  },
  {
    id: '13',
    url: 'https://example.com/article-13',
    title: 'デザインシステムの構築',
    description: '大規模なプロダクトに対応するデザインシステムの作り方',
    thumbnail:
      'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['design-system', 'ui', 'design'],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
    isRead: true,
    readingTime: 20,
    source: 'Design Systems',
  },
  {
    id: '14',
    url: 'https://example.com/article-14',
    title: 'テスト駆動開発入門',
    description: 'TDD の基本概念と実践的な適用方法について',
    thumbnail:
      'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['testing', 'tdd', 'development'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    isRead: true,
    readingTime: 15,
    source: 'Testing Guide',
  },
  {
    id: '15',
    url: 'https://example.com/article-15',
    title: 'マイクロサービス設計パターン',
    description: 'マイクロサービスアーキテクチャの設計パターンと実装',
    thumbnail:
      'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['microservices', 'architecture', 'backend'],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    isRead: true,
    readingTime: 25,
    source: 'Architecture Weekly',
  },
  {
    id: '16',
    url: 'https://example.com/article-16',
    title: 'モバイルファーストデザイン',
    description: 'モバイルファーストアプローチによるレスポンシブデザイン',
    thumbnail:
      'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=400',
    tags: ['mobile-first', 'responsive', 'design'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    isRead: true,
    readingTime: 8,
    source: 'Mobile Design',
  },
];

export const popularTags = [
  'react-native',
  'typescript',
  'design',
  'ai',
  'web',
  'ui-ux',
  'accessibility',
  'performance',
  'security',
  'docker',
  'testing',
  'vue',
  'mobile',
];
